openapi: 3.0.3
info:
  title: Agartex Compilation Service
  description: |-
    This is a server for compiling Latex documents
  version: 0.0.1
servers:
  - url: http://localhost:3300
tags:
  - name: compile
    description: LaTeX document compilation
paths:
  /projects/{projectId}/pdf:
    post:
      security:
        - user_id: []
      parameters:
        - in: path
          name: projectId
          schema:
            type: integer
          required: true
          description: Numeric ID of the affected project
      tags:
        - compile
      summary: Returns the compiled PDF for a given project and compiles it if needed.
      description: |-
        Returns a pdf, which will be compiled if needed. Takes in options to control the compilation process.
      operationId: compile
      requestBody:
        description: Compile options
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CompileOptions'
      responses:
        200:
          description: PDF file
          content: 
            application/pdf:
              schema:
                type: string
                format: binary
        400:
          description: Malformed request body
        401:
          description: Unauthorized to execute operation
        415:
          description: Unsupported media type
        422:
          description: Request validation errors (e.g. missing required fields in options)
  /compile:
    post:
      tags:
        - compile 
      summary: Compiles the provided LaTeX text into a pdf file
      description: |-
        Takes in text that should be a valid LaTeX document and returns the compiled PDF.
      operationId: simpleCompile
      requestBody:
        description: Document body
        content:
          text/plain:
            schema:
              type: string
              example: |-
                \documentclass{article}
                \begin{document}
                This will compile successfully.
                \[
                  x = y^2
                \]
                \end{document}
      responses:
        200:
          description: PDF file
          content:
            application/pdf:
              schema:
                type: string
                format: binary
        400:
          description: Malformed request
        415:
          description: Unsupported media type
        422:
          description: Compilation errors
          content:
            text/plain:
              schema: 
                type: string

components:
  schemas:
    CompileOptions:
      type: object
      properties:
        entrypoint:
          type: string
          nullable: true
          example: main.tex
        force:
          type: boolean
          example: false
        text:
          type: string
      required:
        - entrypoint
  securitySchemes:
    user_id:
      type: apiKey
      in: header
      name: X-User-Id
